[supervisord]
nodaemon=true
logfile=/tmp/supervisord.log
user=optexity

[program:xvfb]
command=Xvfb :99 -screen 0 %(ENV_SCREEN_WIDTH)sx%(ENV_SCREEN_HEIGHT)sx24 -ac
autorestart=true
priority=10
user=optexity

[program:openbox]
command=/bin/bash -c 'envsubst < /etc/xdg/openbox/rc.xml.template > /home/optexity/.config/openbox/rc.xml && sleep 2 && openbox --sm-disable'
environment=DISPLAY=":99"
autorestart=true
priority=20
user=optexity

[program:x11vnc]
command=bash -c "sleep 2 && x11vnc -display :99 -forever -shared -nopw -rfbport 5900 -listen 127.0.0.1"
autorestart=true
priority=30
user=optexity

[program:novnc]
command=websockify --web /usr/share/novnc 8080 localhost:5900
autorestart=true
priority=40
user=optexity

[program:controller]
command=bash -c "sleep 3 && optexity inference --port 9000 --child_process_id 0"
directory=/home/optexity/optexity
environment=DISPLAY=":99"
autorestart=true
priority=50
user=optexity